### ISSUE TITLE
Build should error if there is an unmet dependency in vendored app on rebuild

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/npm-install#152] opened 2020-11-18 16:20 UTC
## What happened?

When rebuilding an app with vendored dependencies, the build succeeded despite the app source `node_modules` not containing all the necessary vendored dependencies. The cached `node_modules` were reused, which were missing the needed dependency. The app built successfully but then failed to run.

The expected behaviour here is that the build fails because there are unmet dependencies.

## Reproduction Steps:
1. Install `pack`. I used
    ```
    pack --version
    0.13.1+git-4134cc6.build-1135
    ```
1. Clone [this sample app](https://github.com/paketo-buildpacks/npm-install/tree/main/integration/testdata/unmet_dep)
1. Edit `package.json` in the app to exclude the `"grunt-steroids": "0.2.3"` dependency.
1. Run `npm install` locally. This will populate `node_modules` with the necessary dependencies for the app. It will also update the `package-lock.json` to exclude the removed dependency.
1. `pack build unmet-dep  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.20-base --clear-cache` . This should succeed and use the `npm rebuild` command.
1. Then, re-add the `"grunt-steroids": "0.2.3"` to the `package.json` and run `npm install --package-lock-only`. The app now contains an unmet dependency, but the `package.json` and `package-lock.json` are in sync.
1. Rebuild the app: `pack build unmet-dep  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.20-base`
    The output should contain:

```
[builder] Paketo NPM Install Buildpack 0.2.1
[builder]   Resolving installation process
[builder]     Process inputs:
[builder]       node_modules      -> "Found"
[builder]       npm-cache         -> "Not found"
[builder]       package-lock.json -> "Found"
[builder]
[builder]     Selected NPM build process: 'npm rebuild'
[builder]
[builder]   Reusing cached layer /layers/paketo-buildpacks_npm-install/modules
[builder]
```

The buildpack reuses the cached version of the node_modules which does not contain the `grunt_steroids` dependency, rather than failing with an unmet dependencies error. If you then run 
```
pack build unmet-dep  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.20-base --clear-cache
```
The build will fail with an error that makes sense:

```
[builder] vendored node_modules have unmet dependencies: npm list failed: exit status 1
[builder]     | +-- serve-static@1.14.1
[builder]     | | +-- encodeurl@1.0.2 deduped
[builder]     | | +-- escape-html@1.0.3 deduped
[builder]     | | +-- parseurl@1.3.3 deduped
[builder]     | | `-- send@0.17.1 deduped
[builder]     | +-- setprototypeof@1.1.1
[builder]     | +-- statuses@1.5.0
[builder]     | +-- type-is@1.6.18
[builder]     | | +-- media-typer@0.3.0
[builder]     | | `-- mime-types@2.1.27 deduped
[builder]     | +-- utils-merge@1.0.1
[builder]     | `-- vary@1.1.2
[builder]     +-- UNMET DEPENDENCY grunt-steroids@0.2.3
[builder]     | +-- UNMET DEPENDENCY chalk@0.3.0
[builder]     | | +-- UNMET DEPENDENCY ansi-styles@0.2.0
[builder]     | | `-- UNMET DEPENDENCY has-color@0.1.7
[builder]     | +-- UNMET DEPENDENCY lodash@2.4.1
[builder]     | +-- UNMET DEPENDENCY wrench@1.5.4
[builder]     | `-- UNMET DEPENDENCY xml2js@0.4.1
[builder]     |   +-- UNMET DEPENDENCY sax@0.5.8
[builder]     |   `-- UNMET DEPENDENCY xmlbuilder@15.1.1
[builder]     `-- logfmt@1.3.2
[builder]       +-- split@0.2.10
[builder]       | `-- through@2.3.8 deduped
[builder]       `-- through@2.3.8
[builder]
[builder]     npm ERR! missing: grunt-steroids@0.2.3, required by node_web_app@0.0.0
[builder]     npm ERR! missing: chalk@0.3.0, required by grunt-steroids@0.2.3
[builder]     npm ERR! missing: lodash@2.4.1, required by grunt-steroids@0.2.3
[builder]     npm ERR! missing: wrench@1.5.4, required by grunt-steroids@0.2.3
[builder]     npm ERR! missing: xml2js@0.4.1, required by grunt-steroids@0.2.3
[builder]     npm ERR! missing: ansi-styles@0.2.0, required by chalk@0.3.0
[builder]     npm ERR! missing: has-color@0.1.7, required by chalk@0.3.0
[builder]     npm ERR! missing: sax@0.5.8, required by xml2js@0.4.1
[builder]     npm ERR! missing: xmlbuilder@15.1.1, required by xml2js@0.4.1
```
## Checklist

Please confirm the following:

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by arjun024** [comment] 2020-11-19 16:14
Thanks for filing the issue with detailed steps. Looks like the caching is just done based on `node_install` which seems wrong.

**Comment by fg-j** [comment] 2021-11-30 15:54
@paketo-buildpacks/nodejs-maintainers This has been open for a while. Are there blockers? @arjun024 Can you explain a bit more what you mean by "caching is just done based on node_install"? Do you have ideas for better caching criteria?

**Comment by arjun024** [comment] 2022-08-25 16:32
Sorry I didn't notice the mention. I'm unable to remember the exact context. From @modulo11's comment it looks like this should be closed

**Comment by c0d1ngm0nk3y** [comment] 2023-03-03 15:42
I was able to reproduce it with the exact reproduction using gcr.io/paketo-buildpacks/nodejs:0.0.10 (Node.js v10).

But I was not able to reproduce it with gcr.io/paketo-buildpacks/nodejs:1.3.1 (Node.js v18), now even with using the cache, it fails with

```console
[builder]   Executing launch environment install process
[builder]     npm ERR! code ELSPROBLEMS
[builder]     npm ERR! missing: grunt-steroids@0.2.3, required by sample-nodejs@1.0.0
[builder]     sample-nodejs@1.0.0 /workspace
[builder]     +-- @sap/xsenv@3.4.0
[builder]     +-- express@4.18.2
[builder]     +-- UNMET DEPENDENCY grunt-steroids@0.2.3
```

Which is the expected outcome. So I will close the issue.

**Closed by c0d1ngm0nk3y** 2023-03-03 15:42 UTC
Labels: bug
