### ISSUE TITLE
When using project.toml to specify included source files I get the error  "unlinkat /workspace/node_modules/end-of-stream/package.json: permission denied"

### ISSUE THREAD

**Issue by bervol** [paketo-buildpacks/npm-install#171] opened 2020-12-22 13:37 UTC
## What happened?

I have added a `project.toml` file to my project that looks like this:
```toml
[build]
include = [
    "src",
    "package.json",
    "package-lock.json",
    "nest-cli.json",
    "tsconfig.*json",
]
```
Now when I run 
```bash
pack build buildpack-nodejs-poc --builder paketobuildpacks/builder:base
```
my pack build fails with this error message:
```
Paketo Node Engine Buildpack 0.1.4
  Resolving Node Engine version
    Candidate version sources (in priority order):
                -> ""
      <unknown> -> "*"

    Selected Node Engine version (using ): 14.15.1

  Reusing cached layer /layers/paketo-buildpacks_node-engine/node

Paketo NPM Install Buildpack 0.2.3
  Resolving installation process
    Process inputs:
      node_modules      -> "Found"
      npm-cache         -> "Not found"
      package-lock.json -> "Found"

    Selected NPM build process: 'npm rebuild'

  Executing build process
unlinkat /workspace/node_modules/end-of-stream/package.json: permission denied
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

You can easily reproduce the error with this GitHub repository: https://github.com/bernhardvollnhofer/buildpack-nodejs-poc

* What were you attempting to do?
I attempted to only include some source directories in my build.

* What did you expect to happen?
I expected my build to finish successfully.

* What was the actual behavior? Please provide log output, if possible.
```
unlinkat /workspace/node_modules/end-of-stream/package.json: permission denied
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 145
```

## Build Configuration

Please provide some details about your build configuration.

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you using? Please include a version.
```bash
$ pack version
0.15.1+git-79adc30.build-1660
```

* What buildpacks are you using? Please include versions.
I use the auto-detected buildpacks.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?
I use `paketobuildpacks/builder:base`.

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
Here is a GitHub repo where the issue can be reproduced: https://github.com/bernhardvollnhofer/buildpack-nodejs-poc

## Checklist

Please confirm the following:

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

**Comment by arjun024** [comment] 2021-01-29 19:27
I'm not able to reproduce this issue. I build your project from your repo and works out successfully for me.
I see in your input that you have
```
    Process inputs:
      node_modules      -> "Found"
```
though your repo does not have a `node_modules`. Did you run other commands (like `npm i`) before running pack build?

**Comment by thitch97** [comment] 2021-01-29 21:59
Closing this for now as the issue seems to be addressed by https://github.com/buildpacks/pack/pull/1043. Please feel free to reopen this issue if the problem persists.

**Closed by thitch97** 2021-01-29 21:59 UTC
